### PR TITLE
Accession enum changes 

### PR DESCRIPTION
**Pull request by ucancallmealicia**

### CODE REVIEW

**Comment by ucancallmealicia** [comment]
I think we are good - the next commit fixes the dupe entry

**Comment by triplingual** [comment]
In the next commit, though, there's still [line 73](https://github.com/YaleArchivesSpace/yale_pui_customizations/blob/c80954769171832c40de74fe8ab1bfe2e22ff62e/public/locales/en.yml#L73) that has just "Unprocessed Records". Should it be "Unprocessed/Unavailable Records"?

**Comment by ucancallmealicia** [comment]
Ah ok, I thought the comment was just referring to the previous commit, sorry! I left that value as-is because I thought it sounded even more awkward than the other changes, and because there are very few cases when that label would appear - most if not all of the published accessions aren't linked to a resource

**Comment by triplingual** [comment]
OK -- we can move forward with this as is and change quickly if need be.

**Pull request merged**
